FROM kaazing/enterprise-gateway:latest

# Add broker specific client libs for ActiveMQ

ADD http://central.maven.org/maven2/org/apache/activemq/activemq-client/5.14.1/activemq-client-5.14.1.jar lib/ext/

ADD http://central.maven.org/maven2/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1/geronimo-jms_1.1_spec-1.1.jar lib/ext/
ADD http://central.maven.org/maven2/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar lib/ext/

ADD http://central.maven.org/maven2/org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1/geronimo-jta_1.1_spec-1.1.jar lib/ext/
ADD http://central.maven.org/maven2/org/fusesource/hawtbuf/hawtbuf/1.10/hawtbuf-1.10.jar lib/ext/
